### ISSUE TITLE
Matrix Transpose

### ISSUE THREAD

**Issue by russbramblett** [xuzs9298/CGEpy#1]
It looks like there is a function to transpose a matrix beginning on line 1173. Is there a reason why we can't use the numpy._matrix_.transpose() function?

**Comment by xuzs9298** [comment]
1. Transposing our data structure should also switch labels for the rows and the cols.
2. The numpy.matrix.transpose() doesn't do deep copy, we need a deep copy for the expression..

**Comment by russbramblett** [comment]
Makes sense.
