### ISSUE TITLE
Some equation may be wrong.

### ISSUE THREAD

**Issue by xuzs9298** [xuzs9298/CGEpy#10]
I just identified that some equations could be wrong due to the same labelling in GAMS. For instance, I and J in GAMS are the same labels with different names, that would be confusing in a matrix that's I * J

**Comment by russbramblett** [comment]
I'm sort of stuck. I've tried a bunch of "fixes" but to no avail. 

Are you making any headway?

**Comment by xuzs9298** [comment]
I fixed a couple of it.(CHEQ, VEQ) Some still needs to fix. 
Usually it's fixed by a reverse ( ~ ), or select the row or column to sum/prod.

I made some changes to the code:
equation.test(avl.initialVals) will calculate the equation(/ matrix) with the initial values, it will output (row# ,col#, value) for each equation in the matrix, the values should be all 0.

.sum() .prod() can now take 0 or 1 to indicate row to col to sum, in case they are the same labels.

Commented test statement without any following print statement means I already verified this equation.

Some problems that you can help me with:

1. for PVAEQ, I stuck on it for a while. It seem to me that I have fixed the equation to the correct form, but there are a couple values that's not 0, 0.02 and 0.005, it's not big, but maybe it's some mistake that made it non-zero. Every equation else got much closer to 0. Can you examine this equation?

2. FDEQ(F,I), there should be no same label issue in the equation. But the output has many non-zero values. I think the SUM(GF,TAUFX(GF,F,I) ) is incorrect.

**Comment by russbramblett** [comment]
I'm looking into it. There are clearly some issues but going through the equations, the issue isn't clear yet. Hopefully I can get it tonight or tomorrow.

**Comment by russbramblett** [comment]
So... for FDEQ I mistakenly used " * " when I should've used " + ". Part two is good now.

**Comment by russbramblett** [comment]
I meant that I fixed GFEQ. I'll start on FDEQ.

**Comment by xuzs9298** [comment]
I checked all other equations. 

Beside the 2 mentioned above. One more equation that doesn't hold true is YGEQ(GX) (the very long one).

I suspect that there are other problems causing the solver to not finish success. I'll look into it.

**Comment by russbramblett** [comment]
Yeah, I think you're right. I tried removing all the constraints that didn't hold and then shortened the variable list to match the constraints... and I ended up with the same error.

**Comment by xuzs9298** [comment]
Hi Russ,

I found a way to jump over this problem. I tried many ways to solve the 'Singular matrix C in LSQ subproblem',  but whenever I keep 2 or more equations in the constraints, the problem is there. I tried different bounds, different combinations, etc.

It worked well with inequations. So I made each equation to be 2 inequations(669-670, libs.py). It now works well to me, takes about 10 min to run.

The following is the list of the equations that didn't hold with initial values:
PVAEQ
FDEQ
LSEQ1(H)
YGEQ(GX)

I believe if we fixed the mistakes in these equations, the model should be correct.

**Comment by xuzs9298** [comment]
P.S. If I remove the bnds from the last commit. the solver will run much longer, I waited 1 hour with no output. That's reasonable because we're lacking constraints and maybe there's no solution. So I set the bounds somewhere near the initial values.

**Comment by russbramblett** [comment]
Awesome.

**Comment by russbramblett** [comment]
What happens if we remove SPI from the constraint list? Since it's the objective function, it doesn't seem like it belongs in the list... I tried to minimize without it and the only value that was different than the initial value was x[1176]. I'm not sure what to think about that.

Also, what is  "1e-3"  doing in 669-670?

**Comment by xuzs9298** [comment]
It should be in the list:

Here's an example:

Case 1: 
variables: x1, x2, x3
obj function: lambda x: x1 + x2 +x3

Case 2:
variables: x1, x2, x3, x4
constraint: x4 = x1 + x2 + x3
obj function: lambda x: x4

The two examples above are mathematically equivalent. By putting SPI in the constraint list, we are following the format of case 2.

1176 is the SPI value index.
It's normal that only difference is x[1176]. If you remove the constraint, since the constraint is gone, so the obj function will only try the bounds put on x[1176](which I set it to be +- 0.1 from the initial value), so the only changed will be on x[1176].

///////////////////////////////

1e-3 is 0.001. Before, we have equations, we can set some value v = 0. In inequations, we need to set v<0.001 and v > 0.001. That's what 1e-3 is doing. And we can adjust to higher precision in case we need to.

**Comment by russbramblett** [comment]
I'm with you on the math... but when SPI is in the constraints, to me it looks like we are adding an unnecessary constraint:
max: y = x[1] - x[2] + x[3]
s.t. 
y = x[1] - x[2] + x[3]
x[1] =  x[2] - x[3]

Either way, one additional constraint shouldn't make much of a difference.
