### ISSUE TITLE
Initialize Variables

### ISSUE THREAD

**Issue by dbranham** [xuzs9298/CGEpy#2]
Should we be initializing the variables such as P and CH? I ask because some of them are used in multiple different constraints, and they should all be the same thing, rather than just creating a new one each time.

**Comment by dbranham** [comment]
If this is taken care of by using this avl object, then that works and we can close this

**Comment by xuzs9298** [comment]
I haven't done that part yet. We can do that by assigning values to
initialVals.

initialVals = [1 for i in range(avl.nvars)]
results = minimize(fun(0), initialVals, method='SLSQP', bounds=bnds,
constraints=cons)
