### ISSUE TITLE
avl.add

### ISSUE THREAD

**Issue by xuzs9298** [xuzs9298/CGEpy#5]
In avl.add(), the second argument(initialized value) should have the .loc to make it the same size as the variable. Otherwise, avl.nvars != len(avl.initialVals)

For example: DD0 have more rows then I.
avl.add('DD', DD0, I) should be
avl.add('DD', DD0.loc[I], I)

I have changed the ones that size doesn't match. I think the other ones also need to be changed to be consistent.

**Comment by dbranham** [comment]
Good catch
