### ISSUE TITLE
GAMS conditional ($)

### ISSUE THREAD

**Issue by russbramblett** [xuzs9298/CGEpy#8]
The dollar sign is basically an 'If' statement in GAMS. 
 
Near line 1190:
TDEQ(G,GX)$(IGTD(G,GX) EQ 1)..
This reads, "assign TDEQ(G, GX) if (IGTD(G,GX) == 1"

It took a while to find this:
![dollarsign](https://cloud.githubusercontent.com/assets/19451734/15992960/7052942c-3096-11e6-86bf-4c81e136aec9.png)

https://comp.uark.edu/~rrardin/oorbook/software/gams/notes.html

If a condition is not given, the default,  != 0, is used (I'm about 95% sure of this. I couldn't find it in the documentation).

Near line 1057:
DEQ(I)$PWM0(I)..
This reads, "initialize DEQ(I) if PWM0(I) != 0"

Near line 1008:
DELTA(I)*PROD(F$ALPHA(F,I),(FD(F,I))**ALPHA(F,I))
This reads, "calculated the product ALPHA(F,I),(FD(F,I))**ALPHA(F,I) if ALPHA(F,I),(FD(F,I))**ALPHA(F,I) != 0"

**Comment by xuzs9298** [comment]
Problem solved.
