### ISSUE TITLE
nan errors so the minimize function isn't working

### ISSUE THREAD

**Issue by xuzs9298** [xuzs9298/CGEpy#9]
Hi Russ,

The nan errors comes from nans in the TAUFX ( looks like from line 989 - 994), when making equation from TAUFX, the nans in the matrix will be printed to the equation.

The line3 and line5 of YGEQ now looks correct to me. I iterate through GX to set one element in the vector of GX at a time.

Line6 and line7 needs 3-d data from TAUFX, but you created it to be 2d and without the GX labels. So i'm not sure what to do.

**Comment by russbramblett** [comment]
I assumed summing the GF axis would collapse TAUFX down to a 2d matrix.

**Comment by russbramblett** [comment]
I'll re-write the matrix with GX labels

**Comment by xuzs9298** [comment]
That would be great, You can store the 3rd dimension using a dictionary like this: {'GX label1' : dataframe1, 'GX label2': dataframe2}

**Comment by russbramblett** [comment]
It isn't quite right, but it should work in your equation now.

**Comment by xuzs9298** [comment]
The nan problem is because of the TAUFX.loc[F,I] on line 1008, TAUFX itself doesn't have nans in it, but TAUFX.loc[F,I] does. I added fillna(0.0) to make it working.  But the minimize function takes forever on my laptop. 

Should we also set the bounds in the minimize function?

**Comment by xuzs9298** [comment]
I just got some results. It outputs all 0s. It just takes very long to run.

**Comment by dbranham** [comment]
Well that's good news!

**Comment by russbramblett** [comment]
I printed out the results of the minimize and it looks like we still have a few issues to deal with:

fun: -867.85440241413198
jac: array([ 0.,  0.,  0., ...,  0.,  0.,  0.])
message: 'Singular matrix C in LSQ subproblem'
nfev: 1458
nit: 1
njev: 1
status: 6
success: False
x: array([ 0.,  0.,  0., ...,  1.,  1.,  1.])

**Comment by xuzs9298** [comment]
Hi Russ,

Do you have any idea what could caused it to have this problem?
I'll double check the equations so that for the given initial vals, the equation is correct.

**Comment by russbramblett** [comment]
When you print out the constraints and the objective function, they look a bit odd:

objFun: <function <lambda> at 0x000001E7A622B7B8>
cons:  {'type': 'eq', 'fun': <function ExprM.write.<locals>.<lambda> at 0x00000204F4D89730>}

That could be part of it.

**Comment by xuzs9298** [comment]
Just to verify my understanding is correct. The equation should be satisfied with the initial values, correct? 

It's printing out the address, since the 'fun' is a function.
To see what's the equation you can print the ExprM class.
Once it's written into cons, it will become part of a function and is not printable.

**Comment by russbramblett** [comment]
Yes, you are correct. 

No printing? I'll have to rethink my troubleshooting methodology.

**Comment by russbramblett** [comment]
Could it be an issue that the objective function is part of the constraint list?

**Comment by xuzs9298** [comment]
The objects function is "lambda x: -1 * x[avl.getIndex('SPI')]" which is the -SPI. I don't think there's a problem with that.

**Comment by xuzs9298** [comment]
I think some equation is wrong and that's why it's taking so much time. It's spending time to solve the wrong equations. If the initial values should satisfy the equations, it will end after a few iterations.

We haven't checked the equation with the initial values. So I'll start to do that.
